services:
  - docker

before_install:
  - docker pull archlinux/base

script:
  - docker run -v $(pwd):/build -w /build archlinux/base /bin/bash -c "pacman -Syu grub --noconfirm && bash build.sh"

before_deploy:
  - export FILE_TO_UPLOAD="$(pwd)/out/bootia32.efi"

deploy:
  provider: releases
  api_key: $OAUTH_KEY
  file: $FILE_TO_UPLOAD
  skip_cleanup: true
  on:
    tags: true
