language: minimal

branches:
  only:
  - master

services:
    - docker

before_install:
    - echo 'Europe/Minsk' | sudo tee /etc/timezone
    - sudo dpkg-reconfigure --frontend noninteractive tzdata
    - docker pull archlinux/base

script:
    - docker run -e TZ=Europe/Minsk -v $(pwd):/build -w /build archlinux/base /bin/bash -c "pacman -Syu grub --noconfirm && bash build.sh"

before_deploy:
    - git config --local user.name "ElXreno"
    - git config --local user.email "elxreno@gmail.com"
    - export TRAVIS_TAG="$(cat out/fslabel)"
    - git tag -a $TRAVIS_TAG -m "* $(cat out/fslabel)"

deploy:
    provider: releases
    api_key: $OAUTH_KEY
    file: "out/bootia32.efi"
    skip_cleanup: true
    on:
        tags: false
